id: P82FD8613
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG1795
  instance_id: http://purl.bdrc.io/resource/IE1KG1795
  collection_id: http://purl.bdrc.io/resource/PR0ET005
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - སྤྱོད་འཇུག་གི་འགྲེལ་པ་ལེགས་པར་བཤད་པའི་རྒྱ་མཚོ།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - ru pu sa xing lun shi san yan zhi hai
  author: http://purl.bdrc.io/resource/P1830
  publisher: KarmaDelek
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    44223cb2ea3d44bd96bb6e0eb87dfcb9:
      title: ༄༅།་།བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་འགྲེལ་པ་ལེགས་པར་བཤད་པའི་རྒྱ་མཚོ་ཞེས་བྱ་བ་བཞུགས་སོ།་།དང་པོ།ཀླད་ཀྱི་དོན་བཤད་པ།
      volume_number: 6
      base_file: UT1KG1795_006_0000.txt
      reference: http://purl.bdrc.io/resource/VL5ACADAAD442CBB1E
      image_group: null
      quality: null
    ae29a2e640234b3d8fd54eb9d885387c:
      title: དཔེ་སྐྲུན་གསལ་བཤད།
      volume_number: 1
      base_file: UT1KG1795_001_0000.txt
      reference: http://purl.bdrc.io/resource/VLBC610B11A68DAF6A
      image_group: null
      quality: null
    15179610e6bd4bb9814503e1504288c8:
      title: གི་ཤ་ལ་སོགས་པ་གཏོང་བ་དེ་ལ་དཀའ་བ་ཅི་ཞིག་ཡོད།གཉིས་པ་ནི།འཁོར་བ་ཇི་སྲིད་པ་གཞན་གྱི་ཕྱིར་དཀའ་སྤྱད་དགོས་པས་སྡུག་བསྔལ་གྱིས་སྐྱོ་བར་འགྱུར
      volume_number: 7
      base_file: UT1KG1795_007_0000.txt
      reference: http://purl.bdrc.io/resource/VL24A00F0B249CECFF
      image_group: null
      quality: null
    d8abefd41b754faeb8e7441654f3edc8:
      title: བསྡུ་སྒྲིག་གསལ་བཤད།
      volume_number: 3
      base_file: UT1KG1795_003_0000.txt
      reference: http://purl.bdrc.io/resource/VL54983A5BC9432564
      image_group: null
      quality: null
    b7caf39d14864bd78a41fa3d2d7bcc9c:
      title: ༈རྩོམ་པ་པོའི་རྣམ་ཐར་བཞུགས།
      volume_number: 4
      base_file: UT1KG1795_004_0000.txt
      reference: http://purl.bdrc.io/resource/VL38AEBCDEE97BD1E5
      image_group: null
      quality: null
    02483599d8c844f5aad6bd7de058d7f7:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་འགྲེལ་པ་ལེགས་པར་བཤད་པའི་རྒྱ་མཚོ་ཞེས་བྱ་བ་བཞུགས།དང་པོ།ཀླད་ཀྱི་དོན་བཤད་པ།གཉིས་པ།གཞུང་གི་དོན་བ
      volume_number: 5
      base_file: UT1KG1795_005_0000.txt
      reference: http://purl.bdrc.io/resource/VL56B9671A8EB9352F
      image_group: null
      quality: null
    a632598ebbae467482f88671604fe9d2:
      title: སྔོན་འགྲོའི་ཞུ་ཚིགདེ་ཡང་འགྲོ་བ་ལྷ་དང་བཅས་པའི་མ་འདྲིས་པའི་མཛའ་བཤེས།ཕན་བདེའི་རྩ་ལག་ཏུ་གྱུར་པ།བདག་ཅག་གི་སྟོན་པ་མཉམ་མེད་ཐུབ་པའི་དབང་
      volume_number: 2
      base_file: UT1KG1795_002_0000.txt
      reference: http://purl.bdrc.io/resource/VL5C20157275D9F266
      image_group: null
      quality: null
    238a1c5ac1974f1d92d474a29dce431f:
      title: མཁྱེན་བརྩེའི་འོད་སྣང་གི་དཔེ་ཚོགས་བསྡུ་སྒྲིག་ལས་མིའི་མཚན་ཐོ།སྤྱི་ཁྱབ་བསྡུ་སྒྲིག་འགན་ཁུར་བ་གཙོ་བོ།གཟན་དཀར་ཐུབ་བསྟན་ཉི་མ་དང༌།
      volume_number: 8
      base_file: UT1KG1795_008_0000.txt
      reference: http://purl.bdrc.io/resource/VL7D00EC52BAB4DBCA
      image_group: null
      quality: null
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG1795
  - http://purl.bdrc.io/resource/W1KG1795
created_at: '2021-12-24T17:15:46.509026'
last_modified_at: '2021-12-24T17:15:46.509039'
statistics:
  total_words: 67878
  total_non_words: 7295
quality:
  non_words_ratio: 0.11
